use crate::provider::CostConfig;
use serde::{Deserialize, Serialize};
use std::fmt;
use std::sync::Arc;

/// - Doc Comment Style: Triple-slash `///` for public API docs, double-slash `//` for internal comments.
/// - Section Dividers: Use `// ---------------------------------------------------------------------------`
// to visually separate major sections of the

// ---------------------------------------------------------------------------
// Content types: The ATOMIC UNITS of all messages. Every message is composed of Vec<Content>.
// ---------------------------------------------------------------------------

// ═══════════════════════════════════════════════════════
// CONTENT ENUM — the atomic unit of all message payloads
// Every message is composed of Vec<Content> variants.
//
// ── Text ────────────────────────────────────────────────
// Plain string payload sent to/from LLM.
// Example:
//   let c = Content::Text("Summarize this code".to_string());
//
// ── Image ───────────────────────────────────────────────
// Binary image encoded as base64 string (NOT a file path).
// LLMs like GPT-4o receive image bytes inline via base64.
// Example:
//   let c = Content::Image {
//       data: base64::encode(fs::read("pic.png").unwrap()),
//       mime_type: "image/png".to_string(),
//   };
//
// ── Thinking ────────────────────────────────────────────
// Internal chain-of-thought from the LLM (e.g. Claude's
// extended thinking). Visible in UI, never re-sent to LLM.
// Example:
//   let c = Content::Thinking("I should first check the schema...".to_string());
//
// ── ToolCall ────────────────────────────────────────────
// LLM's request to invoke a tool with structured JSON args.
// Example:
//   let c = Content::ToolCall {
//       id: "call_abc123".to_string(),
//       name: "read_file".to_string(),
//       params: json!({ "path": "src/main.rs" }),
//   };
// ═══════════════════════════════════════════════════════
// ═══════════════════════════════════════════════════════
// DERIVE MACROS — auto-generated trait implementations
// #[derive(...)] runs at compile time, zero runtime cost.
//
// Debug      → enables {:?} printing for logging/debug
// Clone      → enables .clone() for deep copying the type
// PartialEq  → enables == / != comparisons between instances
// Serialize  → enables conversion TO json/bytes (serde crate)
// Deserialize→ enables construction FROM json/bytes (serde crate)
//
// Python analogy: like @dataclass(eq=True) + json mixin,
// but declared explicitly and enforced by the compiler.
// ═══════════════════════════════════════════════════════
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")] // serde : for serialization, use the "type" field to determine the variant
pub enum Content {
    #[serde(rename = "text")]
    Text { text: String },
    #[serde(rename = "image")]
    Image {
        data: String,
        #[serde(rename = "mimeType")]
        mime_type: String,
    },
    #[serde(rename = "thinking")]
    Thinking {
        /// The raw thinking/reasoning text generated by the model
        /// before its final response. Visible to the user/UI but
        /// treated as internal monologue — NOT part of the answer.
        thinking: String,

        /// Cryptographic integrity token issued by the LLM provider.
        /// Anthropic: base64 blob called `signature` on the thinking block.
        /// OpenAI:    opaque blob called `encrypted_content` in reasoning items.
        /// Gemini:    opaque blob called `thought_signature`.
        ///
        /// Must be echoed back UNMODIFIED in multi-turn conversations —
        /// the provider uses it to verify the thinking block was not
        /// altered between turns. `None` when provider doesn't support
        /// extended thinking or on first-turn generation.
        #[serde(skip_serializing_if = "Option::is_none")]
        signature: Option<String>, //Option<T> works for any type T in Rust: enum, struct, primitive, or even another Option
    },
    #[serde(rename = "toolCall")]
    ToolCall {
        id: String,
        name: String,
        arguments: serde_json::Value,
    },
}

/* CONCEPTUAL NOTE: ENUMs vs Structs in Rust
- Enums: OR Types
define a type that can be one of several variants, each with its own data.
Perfect for Content, where a block can be Text OR Image OR Thinking, etc.

- Structs: AND Types
define a type that has multiple fields simultaneously.
Perfect for Message, where a message has a role AND content AND timestamp, etc.
 */

// ---------------------------------------------------------------------------
// Messages: The units of conversation between user and assistant.
// Each message has a role (user, assistant, toolResult) and a payload (Vec<Content>).
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "role")]
pub enum Message {
    // The payload of a message is always a Vec<Content> — a sequence of atomic content blocks.
    // Vec<Content> is just Rust's name for a dynamic array (like Python's list) of Content enums.
    //The reason a Message holds a list of Content (not just one) is that a single LLM turn can contain multiple things at once
    // — e.g., a Thinking block followed by a ToolCall followed by Text .
    // Anthropic's extended thinking API is a real example of this:
    // one assistant message = [Thinking("..."), Text("here's my answer")]
    /// User turn — raw input from the human.
    /// Vec<Content> allows mixed media: text + images in one message.
    /// timestamp: unix millis, used for session branching / replay.
    #[serde(rename = "user")]
    User {
        content: Vec<Content>,
        timestamp: u64,
    },

    /// Assistant turn — the LLM's response, fully annotated.
    /// stop_reason tells you WHY generation stopped (tool_call, end_turn, max_tokens).
    /// model/provider/usage are captured here for cost tracking & multi-provider routing.
    /// error_message is optional — a failed turn is still persisted, not dropped.
    #[serde(rename = "assistant")]
    Assistant {
        content: Vec<Content>,
        #[serde(rename = "stopReason")]
        stop_reason: StopReason, //enum defined below: Stop, Length, ToolUse, Error, Aborted
        model: String,
        provider: String,
        usage: Usage, // struct defined below: input/output tokens, cache hits, total tokens
        timestamp: u64,
        #[serde(skip_serializing_if = "Option::is_none")]
        error_message: Option<String>,
    },

    /// Tool execution result — returned to LLM in the next turn.
    /// tool_call_id links this result back to the specific ToolCall in Assistant content.
    /// is_error: true means LLM sees the failure and can recover/retry.
    /// content: Vec<Content> allows rich results — text, images, structured data.
    #[serde(rename = "toolResult")]
    ToolResult {
        #[serde(rename = "toolCallId")]
        tool_call_id: String,
        #[serde(rename = "toolName")]
        tool_name: String,
        content: Vec<Content>,
        #[serde(rename = "isError")]
        is_error: bool,
        timestamp: u64,
    },
}

// Helper constructors for common message types
impl Message {
    // impl Message { ... }	"attach methods to this type". Python analogy: class Message: body — defining methods

    // Helper constructor for a simple user message with just text content. Constructor returns Self.
    // Here it's Self::User { ... } because we're constructing a Message::User variant.
    // The content is a Vec<Content> with one Content::Text block containing the input text.
    // Timestamp is set to now_ms() helper function defined below.
    //****************************************************************************************************
    // The user() constructor is a convenient way to create a Message::User with just text content.
    // NOTE: there is NO constructor for Assistant or ToolResult messages —
    // these require more fields (stop_reason, model, etc.) that must be provided explicitly when constructing those variants.
    // The design lesson: only create constructors where there's a default/common shape worth abstracting. Don't add constructors for complex types just for symmetry.
    pub fn user(text: impl Into<String>) -> Self {
        //impl Into<String> means "accept anything that can be converted into a String"
        // — this makes the API more flexible, allowing both &str and String inputs.
        Self::User {
            // For a simple user message, we wrap the text in a Vec<Content> with one Text block.
            // This allows the API to evolve later to support mixed content (e.g., text + image) without breaking changes.

            // vec! — a macro (the ! means macro not a function. macros generate code at compile time) that creates
            // and populates a Vec in one shot, like Python's [item] literal syntax.
            // Here we create a Vec<Content> with a single Content::Text block containing the user's input text.
            // vec![Content::Text { text: text.into() }] is exactly Python's [Content.Text(text=str(text))] — create a list with one item inside it,
            // where that item is a Content::Text struct with its text field set to the input text.
            content: vec![Content::Text { text: text.into() }],
            timestamp: now_ms(),
        }
    }

    pub fn role(&self) -> &str {
        //& means borrow — "look at this value without taking ownership of it".
        //*************************************************************
        // Rust's ownership model means passing self (no &) would consume and destroy the value after the call.
        // &self : allows us to read the message's role without taking ownership, so we can call this method multiple times or on borrowed references.
        // &mut self : would allow us to modify the message's internal state if needed (not the case here, but useful for methods that change the message).
        // self: would mean "take ownership of the message" — the caller would no longer have access to it after calling role(),
        // which is not what we want for a simple getter method. The self gets deleted after the call, so you can only call it once and can't use the message again.
        // *************************************************************
        // &str on the return side means "return a reference to a string slice that already exists in memory". Similar to borrowing — no allocation, no copy.
        match self {
            // The .. means "ignore the other fields (only signature), we only care about the variant type here"
            Self::User { .. } => "user",
            //The serde vs role() Sync Problem
            // Yes, the strings must match exactly — the LLM API expects "user" in both the serialized JSON and the role field returned by the role() method.
            // This is because the LLM provider uses the "role" field to determine how to process the message (e.g., treat "user" messages as input from the human, "assistant
            Self::Assistant { .. } => "assistant",
            Self::ToolResult { .. } => "toolResult",
        }
    }

    /***************** ALTERNATIVES to role() implementation *****************
    // An althernate version with serde_json::Value for dynamic access to fields, but it's less efficient and more error-prone than the direct match approach above:
    use serde_json::to_value;
    pub fn role(&self) -> String {
        to_value(self)
            .unwrap()["role"]           // reads the serde-serialized "role" key
            .as_str()
            .unwrap()
            .to_string()
    }


    // An althernate more production ready (fault tolerant) implementation of role() that returns a Result and validates the internal consistency of the message:
    use serde_json
    pub fn role(&self) -> Result<String, serde_json::Error> {
        let value = serde_json::to_value(self)?;
        let role = value["role"]
            .as_str()  // as_str() → borrows the string, no memory allocation, just a pointer+length view
            .ok_or_else(|| serde_json::Error::custom("role field missing or not a string"))?;
            // COMMENT - ||: The || pipes are the closure's (similar to  = python'S lambda) empty argument list — |arg1, arg2|
        Ok(role.to_string()) // to_string() creates a new owned String from the borrowed &str, which is what the method signature says we return.
    }

    The caller expects a Result<String, serde_json::Error> and not a string and therefore needs to handle the Result with a "match expression" or the "?" operator.

    Think of "?" as a way to propagate errors up the call stack without having to write explicit error handling code at each step.
    When you call a function that returns a Result, you can append ? to it. If the Result is Ok, it unwraps the value and continues execution.
    If the Result is Err, it immediately returns that error from the current function, effectively propagating it up to the caller.

    Python analogy:
    Think of "? as Python's:
    if result is None:
        raise SomeError("role missing")  # ← that's what ? does
    else:
        role = result
        # continue with role
    */

    //*********************************************************************

    // Helper method to check if an assistant message ended due to context overflow.
    // Using "exhaustive pattern matching" (match; Some(msg); flow to specifc here: crate::provider::is_context_overflow_message(msg))
    // to safely access the CONTEXT OVERFLOW error_message.

    /// Check if this assistant message represents a context overflow error.
    ///
    /// Some providers (SSE-based: Anthropic, OpenAI) return overflow as a
    /// `StopReason::Error` message rather than an HTTP error. This method
    /// checks the `error_message` field against known overflow patterns.
    pub fn is_context_overflow(&self) -> bool {
        match self {
            Self::Assistant {
                stop_reason: StopReason::Error,
                error_message: Some(msg),
                //Some(msg) inside a match arm says: "only enter this branch if error_message is not None,
                // and if so, bind the inner string to the variable msg for use in the arm's body"
                ..
            } => crate::provider::is_context_overflow_message(msg),
            _ => false, // Rust match must be exhaustive — we have to handle all possible variants of Message.
        }
    }
}

// ---------------------------------------------------------------------------
// Stop reasons
// ---------------------------------------------------------------------------

/* StopReason enum captures why an assistant message generation stopped. This is crucial for understanding the LLM's behavior and for debugging.
LLMS vary in how they signal the end of generation — some use explicit stop reasons, others return errors for context overflow, etc.
By standardizing these into a StopReason enum, we can handle them uniformly in the agent loop and UI.
However, providers differ in how they indicate context overflow — some return a StopReason::Error with a specific error message,
while others might have a dedicated stop reason.
Therefore, we also have provider specific implmentation and he is_context_overflow() method on Message to check for overflow conditions in
a provider-agnostic way, by inspecting the error_message field when stop_reason is Error.
*/

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum StopReason {
    Stop,
    Length, //MaxTokens, TokenLimit, ContextOverflow — different providers use different terms for the same underlying reason: the generation
    ToolUse,
    Error,
    Aborted,
    /* Below are the options adopted from other Agentic models and our own experience with LLM APIs.*/
    MaxTurns, // Adopted from: LangGraph, Autogen. Description: Indicates generation stopped because the conversation reached the maximum allowed turns.
    UserStop, // Adopted from: AutoGPT. Description: Indicates generation was stopped by an explicit user command (e.g., "stop", "cancel").
    Handoff, // OpenAI Swarm, Adopted from: AutoGPT. Description: Indicates the agent is handing off to a human operator (e.g., for approval or intervention).
    GuardRail, // Adopted from: Llama Guard, Bedrock. Description: Indicates generation was stopped by an internal guardrail (e.g., content moderation, safety filter) - — different from Aborted
    ContextCompacted, // Adopted from: Anthropic's context compaction feature. Description: Indicates generation stopped because the model compacted the context to fit within limits, which may have caused loss of information.
    Paused, // Adopted from: LangGraph. Description: Indicates generation was paused (e.g., waiting for external input or async operation) rather than fully stopped.
}

//*********** STOP REASON HELPERS ***********
/*
fmt::Display — Rust's "how to print this type as a human-readable string"

Python analogy: implementing __str__(self) on a class.

In Rust, you use fmt::Display instead of __str__. Once implemented, you can:
  - println!("{}", stop_reason)          ← uses Display
  - format!("Stopped: {}", stop_reason) ← uses Display
  - stop_reason.to_string()              ← auto-generated via Display!

The signature:
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result

  &self           — borrow the value (read-only)
  f               — the "output buffer" you write into
  fmt::Result     — Ok(()) if write succeeded, Err if not (rare)
  fmt::Formatter<'_> — '_ is an elided (compiler-inferred) lifetime for the borrow

The write!() macro writes into f (the formatter buffer):
  write!(f, "stop")  ←→  Python's  return "stop"

We implement this manually (instead of deriving) because we want custom
camelCase strings ("toolUse", not "ToolUse") that match the wire protocol.
*/
impl fmt::Display for StopReason {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Stop => write!(f, "stop"),
            Self::Length => write!(f, "length"),
            Self::ToolUse => write!(f, "toolUse"),
            Self::Error => write!(f, "error"),
            Self::Aborted => write!(f, "aborted"),
            Self::MaxTurns => write!(f, "maxTurns"),
            Self::UserStop => write!(f, "userStop"),
            Self::Handoff => write!(f, "handoff"),
            Self::GuardRail => write!(f, "guardRail"),
            Self::ContextCompacted => write!(f, "contextCompacted"),
            Self::Paused => write!(f, "paused"),
        }
    }
}

// ---------------------------------------------------------------------------
// AgentMessage — LLM messages + extensible custom types
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ExtensionMessage {
    pub role: String,
    // Here it'S more like a channel or category for the message, not diretcly "user"/"assistant"/"toolResult".
    // This allows flexibility for app-specific messages (e.g., "notification", "system", "debug") that aren't part of the LLM conversation
    // but still need to be handled in the agent loop and UI.
    // A proper naming should have been "type" or "category" instead of "role",
    // but we use "role" here for consistency with the Message enum's role field and to leverage the same serde tagging mechanism.
    pub kind: String,
    pub data: serde_json::Value,
}

impl ExtensionMessage {
    pub fn new(kind: impl Into<String>, data: impl Serialize) -> Self {
        Self {
            role: "extension".into(),
            kind: kind.into(), // .into() makes a ownable String from the input (which can be &str or String)
            data: serde_json::to_value(data).unwrap_or(serde_json::Value::Null),
            // Convert the input data to a serde_json::Value. If serialization fails, use Null as a fallback.
            // to_value() returns a Result<Value, Error>. unwrap_or(fallback) means "give me the Ok value, or use Null if it failed" — no panic
        }
    }
}

/*
ARCHITECTURE: AgentMessage — the agent loop's two-lane routing envelope

The agent loop operates with two layers of "messages":

  `Message`      = LLM VOCABULARY — the exact types the provider API understands:
                   User, Assistant, ToolResult. Maps 1:1 to the JSON payload
                   sent to the provider. The LLM only ever sees these.

  `AgentMessage` = AGENT VOCABULARY — a routing envelope around Message.
                   Decides: does this content go INTO the LLM context window,
                   or SIDEWAYS to the UI/app without consuming tokens?

WHY TWO LAYERS?
  The agent needs to track content meaningful to the app that must NEVER reach
  the LLM — UI notifications, debug events, session metadata, progress markers.
  Sending these to the LLM would waste the context budget and confuse the model.

  `AgentMessage` solves this with two variants:
    Llm(Message)               — enters the LLM context; serialized into the API request
    Extension(ExtensionMessage) — NEVER enters the context window; only emitted as AgentEvents

  Think of it as a fork in the road: every message must declare which lane it
  belongs to at construction time. Once tagged Extension, it can never leak
  into the LLM context — the type system enforces this rule at compile time.

RUST QUIRK: `#[serde(untagged)]`
  By default, serde serializes enum variants with a discriminator key:
    {"Llm": {"role": "user", ...}} or {"Extension": {"role": "extension", ...}}
  With `#[serde(untagged)]`, the variant wrapper is omitted — only the inner
  value is serialized:
    {"role": "user", ...}       ← Message (Llm variant)
    {"role": "extension", ...}  ← ExtensionMessage (Extension variant)
  Deserialization tries each variant in order until one succeeds. The `role`
  field acts as the natural discriminator: LLM roles ("user"/"assistant"/
  "tool_result") vs the "extension" sentinel value.

RUST QUIRK: Tuple-style variants (Llm(Message), Extension(ExtensionMessage))
  Both variants are tuple-style — each wraps one existing, fully-formed type.
  No field names are needed because the wrapped type is already self-describing.
  This signals design intent: "I am ROUTING this object, not reshaping it."
  Compare to Content::Text { text: String } (struct-style) — that defines a
  NEW data shape. AgentMessage constructs nothing new; it only classifies.

ONE-WAY CONVERSION: `impl From<Message> for AgentMessage`
  Only `Message → AgentMessage::Llm` exists; there is no path for
  ExtensionMessage to become an Llm variant. This is intentional:
  UI-only content can never accidentally slip into the LLM context.
  The compiler catches the mistake — no runtime guard needed.

WHERE AgentMessage IS USED:
  AgentContext.messages         — full conversation history (includes Extension messages)
  AgentEvent::MessageStart/End  — real-time streaming events carry AgentMessage
  AgentEvent::TurnEnd           — the completed turn message
  AgentEvent::AgentEnd          — all new messages produced in a run
  Session history               — Extension messages are part of the full agent story,
                                  not just the LLM's narrower view of it
*/
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AgentMessage {
    /// LLM-bound message — enters the context window and is sent to the provider API.
    Llm(Message),
    /// App-only message — streamed as events but never enters the LLM context window.
    Extension(ExtensionMessage),
}

impl AgentMessage {
    pub fn role(&self) -> &str {
        match self {
            Self::Llm(m) => m.role(),
            Self::Extension(ext) => &ext.role,
            // ext.role is already a String, so we can return a reference to it directly.
            // str vs &str vs String: ext.role is a String (owned, heap-allocated), but the method signature says we return &str (a string slice, borrowed reference).
            // str is never alone type in Rust — it's always &str (a reference to a string slice) or String (an owned string).
            // But Rust still differentiates between &String and &str.
        }
    }

    pub fn as_llm(&self) -> Option<&Message> {
        match self {
            Self::Llm(m) => Some(m), // actually is Some(&m) but Rust allows this shorthand when the types line up
            Self::Extension(_) => None,
            // would have also worked with this syntax: _ => None, since we don't need to use the extension message in this method.
            // The _ is a wildcard that matches any value without binding it to a variable.
        }
    }
}

// One-way: Message → AgentMessage::Llm only. No path exists from ExtensionMessage to Llm.
// See ARCHITECTURE block above for why this asymmetry is intentional.
impl From<Message> for AgentMessage {
    fn from(m: Message) -> Self {
        Self::Llm(m)
    }
}

// ---------------------------------------------------------------------------
// Usage metrics for cost tracking and cache hit rate calculation.
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct Usage {
    pub input: u64,
    pub output: u64,
    /*
    #[serde(default)] means: if this field is missing during deserialization, use its default value instead of erroring.
    To set a custom default, you point serde to a custom function:

    fn default_cache_read() -> u64 { 100 }  // some custom default
    #[serde(default = "default_cache_read")]
    pub cache_read: u64,
    */
    /// Reasoning / thinking tokens — a subset of `output`.
    /// Non-zero only for providers that report reasoning tokens separately
    /// (OpenAI o-series via `completion_tokens_details.reasoning_tokens`,
    /// OpenAI Responses API via `output_token_details.reasoning_tokens`).
    /// Defaults to 0 for all other providers.
    #[serde(default)]
    pub reasoning: u64,
    #[serde(default)]
    pub cache_read: u64,
    #[serde(default)]
    pub cache_write: u64,
    #[serde(default)]
    pub total_tokens: u64,
}

impl Usage {
    /// Estimated dollar cost for this usage given per-million-token rates.
    ///
    /// `reasoning` tokens are already counted in `output`, so they are not
    /// double-charged — the breakdown is purely informational.
    pub fn estimated_cost(&self, cost: &CostConfig) -> f64 {
        (self.input as f64 / 1_000_000.0) * cost.input_per_million
            + (self.output as f64 / 1_000_000.0) * cost.output_per_million
            + (self.cache_read as f64 / 1_000_000.0) * cost.cache_read_per_million
            + (self.cache_write as f64 / 1_000_000.0) * cost.cache_write_per_million
    }

    /// Fraction of input tokens served from cache (0.0–1.0).
    /// Returns 0.0 if no input tokens were processed.
    pub fn cache_hit_rate(&self) -> f64 {
        let total_input = self.input + self.cache_read + self.cache_write;
        if total_input == 0 {
            return 0.0; // early return — guard against division by zero
        }
        /*
        RUST QUIRK: Explicit numeric casting with `as`

        Unlike Python, Rust never silently promotes integer types to float.
        self.cache_read and total_input are u64 (unsigned 64-bit integer).
        Division of u64 / u64 = u64 (integer division, truncates decimals).
        To get a fractional result, we must explicitly cast to f64 first.

          self.cache_read as f64   ← safe widening cast: u64 → f64, no data loss
          total_input as f64       ← same

        Python equivalent: float(self.cache_read) / float(total_input)

        `as` in Rust is the casting keyword. For widening casts (small → large type)
        it is always safe. For narrowing casts (large → small), it silently truncates
        (no panic), so be careful when casting from f64 → u64.
        */
        self.cache_read as f64 / total_input as f64
    }
}

// ---------------------------------------------------------------------------
// Cache configuration
// ---------------------------------------------------------------------------

/// Controls prompt caching behavior for providers that support it.
///
/// By default, caching is enabled with automatic breakpoint placement.
/// This gives optimal cost savings without any user configuration.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CacheConfig {
    /// Master switch — set to false to disable all caching hints.
    /// Default: true.
    pub enabled: bool,
    /// How cache breakpoints are placed.
    pub strategy: CacheStrategy,
}

/*
RUST QUIRK: impl Default

Rust does NOT allow default field values in struct definitions (unlike C++/Python dataclasses).
Instead, you implement the `Default` trait, which defines a single method `default() -> Self`
that constructs the "zeroed/sensible" value.

Python analogy:
    @dataclass
    class CacheConfig:
        enabled: bool = True
        strategy: CacheStrategy = CacheStrategy.Auto

    # In Python, defaults live in the field definition.
    # In Rust, defaults live in `impl Default`.

Usage:
    let cfg = CacheConfig::default();    // explicit
    let cfg: CacheConfig = Default::default(); // via trait
    let cfg = CacheConfig { enabled: false, ..Default::default() }; // spread/override
    // The `..Default::default()` is Rust's "struct update syntax" —
    // fill all unspecified fields from the default value.

When you #[derive(Default)], Rust auto-generates this impl by calling `.default()`
on each field. We implement it manually here because we want non-zero defaults
(enabled: true, strategy: Auto) instead of (false, first-variant).
*/
impl Default for CacheConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            strategy: CacheStrategy::Auto,
        }
    }
}

// --------------------------------------------------------------------------
// Cache strategies for providers that support EXPLICIT prompt caching
// (e.g., Anthropic)
// --------------------------------------------------------------------------
/// Strategy for placing cache breakpoints (currently Anthropic-specific;
/// other providers handle caching automatically regardless of this setting).
/// In Future, a provider specific implementation of the agent loop
/// can inspect this setting and apply it to any provider that supports
/// explicit caching hints.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum CacheStrategy {
    /// Automatic breakpoint placement (recommended).
    /// Caches: system prompt, tool definitions, and recent conversation history.
    #[default]
    Auto,
    /// Disable caching entirely.
    Disabled,
    /// Fine-grained control over what gets cached.
    Manual {
        // Inline struct variants or just struct variants are used when you want to group multiple related fields together under a single variant.
        // In this case, Manual has three boolean fields that control different aspects of caching, so it makes sense to group them together.
        // Optional fields must be defines as Option<T> — this allows them to be None (not provided) or Some(value).
        /// Cache the system prompt.
        cache_system: bool,
        /// Cache tool definitions.
        cache_tools: bool,
        /// Cache conversation history (second-to-last message).
        cache_messages: bool,
    },
}

// ---------------------------------------------------------------------------
// Thinking level
// ---------------------------------------------------------------------------

/// Controls the depth of model reasoning before responding.
///
/// - `Off`     — No thinking tokens; pure response, fastest & cheapest.
/// - `Minimal` — Lightest reasoning pass; good for simple tool calls.
/// - `Low`     — Shallow chain-of-thought; for moderately complex tasks.
/// - `Medium`  — Balanced reasoning; default for most agentic workflows.
/// - `High`    — Maximum reasoning budget; for complex multi-step planning.
///   Most expensive — use for hard coding/logic problems only.
///
/// The exact token budgets behind each level are mapped per provider in
/// their respective StreamProvider implementations, and may evolve over time
/// as we optimize for cost vs performance.

/*
RUST QUIRK: Copy vs Clone

`Copy` is a marker trait for types that can be duplicated by just copying their bits
(no heap allocation involved). When a type is Copy, assignment does NOT move ownership —
it silently makes a duplicate.

    let level = ThinkingLevel::Off;
    let also_level = level;   // ← if NOT Copy: move (level is gone)
    let also_level = level;   // ← if Copy: silent bitwise copy (both valid)

ThinkingLevel is a simple enum with no heap data — all variants are just tags.
So it gets `Copy`. This means you can pass it around freely without `clone()` calls.

`Clone` (also derived here) is the explicit, potentially expensive version:
  .clone()  ←  always works, may allocate
  Copy      ←  implicit, zero-cost, only for stack-only types

Python has no equivalent — everything is a reference by default. The closest
analogy is an IntEnum: copying an IntEnum gives you an independent value,
not a shared reference.

`#[default]` on `Off` tells `#[derive(Default)]` which variant to use
when Default::default() is called. Without it, Default would not compile
on an enum (there's no obvious "zero value" for arbitrary enums).
*/
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum ThinkingLevel {
    /// No chain-of-thought tokens. Fastest and cheapest.
    #[default]
    Off,
    Minimal,
    Low,
    Medium,
    High,
}

// ---------------------------------------------------------------------------
// Tool execution strategy
// ---------------------------------------------------------------------------

/// Controls how multiple tool calls from a single LLM response are executed.
///
/// When the LLM returns multiple tool calls (e.g., "read file A, read file B,
/// run bash C"), this determines whether they run sequentially or in parallel.
/// Who Chooses the Strategy?
/// The caller/developer sets it at agent construction time — it's a config on
/// the Agent struct, not a per-turn LLM decision . The LLM has no awareness of it whatsoever.
/// The practical decision rule is straightforward:
/// Parallel — default, stateless tools (file reads, web fetches)
/// Sequential — tools with shared mutable state (DB writes, shell with side effects)
/// Batched — human-in-the-loop flows with periodic steering checkpoints without fully serializing execution
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum ToolExecutionStrategy {
    /// Run tools one at a time, check steering between each.
    /// Use for debugging or tools with shared mutable state.
    Sequential,
    /// Run all tool calls concurrently, check steering after all complete.
    /// Default — most tool calls are independent and this gives the best latency.
    #[default]
    Parallel,
    /// Run in batches of N (N tools in parallel, wait for all N to finish),check steering between batches.
    /// Balances speed with human-in-the-loop control.
    //  Steering: steering is the human-in-the-loop interrupt mechanism .
    //  It's a check point where the agent asks: "has the human sent
    //  a new instruction, cancellation, or correction since the last batch finished?"
    Batched { size: usize },
}

// ---------------------------------------------------------------------------
// Tool Usage and execution context
// ---------------------------------------------------------------------------

/// Callback for streaming partial results during tool execution.
///
/// Tools call this to emit progress updates (e.g., partial output, status messages)
/// that are forwarded as `AgentEvent::ToolExecutionUpdate` events for UI consumption.
/// Partial results are **not** sent to the LLM — only the final `ToolResult` is.
/*  dyn → "I don't know the concrete type at compile time"
//  Fn(ToolResult) → "a function (callable like Python Lambda) that takes a ToolResult as input and returns () (nothing)"
//  Arc<...> → (Atomically Reference Counted) A "thread-safe reference-counted pointer to this function, allowing it to be shared across threads safely"
//  Reference counting means the Arc tracks how many owners currently hold a reference to the value .
    Thread A clones Arc  → count = 2
    Thread B clones Arc  → count = 3
    Thread A drops it    → count = 2
    Thread B drops it    → count = 1
    Original drops it    → count = 0 → memory freed
//  In Rust, one can't just share a raw pointer across threads — Arc wraps the value and keeps a reference count, freeing it when the last owner drops it.
//  Send + Sync → "the function can be safely sent to and called from multiple threads"
//  Send = "safe to move to another thread"
//  Sync = "safe to share a reference across threads"
//  In Rust, the Send and Sync are derived "almost" for free.
//  You only lose it when you use inherently non-thread-safe types like Rc<T> (use Arc<T> instead) or RefCell<T> (use Mutex<T> instead).
//  "+" = "must implement ALL of these"
//  */
pub type ToolUpdateFn = Arc<dyn Fn(ToolResult) + Send + Sync>;

/// Callback for emitting user-facing progress messages during tool execution.
///
/// Each invocation emits an `AgentEvent::ProgressMessage` event. Unlike `ToolUpdateFn`,
/// these are simple text messages intended for user-facing display (e.g., status lines,
/// notifications), not structured tool results.
pub type ProgressFn = Arc<dyn Fn(String) + Send + Sync>;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolResult {
    /*
    The struct ToolResult is a generic result container (content + freeform details) used at execution time — what a tool hands back to the runtime.
    The Message::ToolResult enum variant is a LLM-protocol record — it adds tool_call_id, tool_name, is_error,
    timestamp which are needed for LLM correlation, not tool execution .
    So the runtime transforms struct ToolResult → Message::ToolResult by enriching it with correlation metadata before it enters the LLM conversation.
    */
    pub content: Vec<Content>,
    #[serde(default)]
    pub details: serde_json::Value,
    /// Set by sub-agent tools to the child loop's `loop_id` after `agent_loop()` returns.
    /// `None` for all regular (non-sub-agent) tools.
    /// Propagated to `AgentEvent::ToolExecutionEnd.child_loop_id` so the parent event stream
    /// can reference the child loop without parsing tool result content.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub child_loop_id: Option<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum ToolError {
    /*
    {0} means "insert the first (and only) field of this enum variant" —
    so Failed("disk full") would display as "disk full", and NotFound("bash") displays as "Tool not found: bash"
    */
    #[error("{0}")]
    Failed(String),
    #[error("Tool not found: {0}")]
    NotFound(String),
    #[error("Invalid arguments: {0}")]
    InvalidArgs(String),
    #[error("Cancelled")]
    Cancelled,
}

/// Context passed to tool execution. Bundles all per-invocation state.
///
/// Using a struct instead of individual parameters future-proofs the trait —
/// adding fields to `ToolContext` is non-breaking.
pub struct ToolContext {
    /// The ID of this tool call (for correlation).
    pub tool_call_id: String,
    /// The name of the tool being invoked.
    pub tool_name: String,
    /// Cancellation token — check `is_cancelled()` in long-running tools.
    pub cancel: tokio_util::sync::CancellationToken,
    /// Optional callback for streaming partial `ToolResult`s (UI/logging only).
    /*
    How it works in practice:
    // Somewhere in agent_loop.rs, BEFORE calling the tool:
    let (tx, rx) = channel();  // a pipe

    let on_update = Arc::new(move |partial: ToolResult| {
        tx.send(AgentEvent::ToolExecutionUpdate(partial)); // ← pushes into channel
    });

    // Tool receives the context with on_update already wired:
    let ctx = ToolContext { on_update: Some(on_update), .. };
    tool.execute(params, ctx).await;

    // Meanwhile, the event stream consumer reads from rx → sends to UI

    (tx, rx) is the pipe (the channel)

    ToolUpdateFn is the handle the tool receives — an Arc-wrapped callable that internally calls tx.send(...)

    The tool calls the handle
    → handle pushes into tx
    → wrapping it as AgentEvent::ToolExecutionUpdate(partial)
    → runtime reads from rx
    → dispatches as it wishes (UI, logging, etc.)

    */
    pub on_update: Option<ToolUpdateFn>,
    /// Optional callback for emitting user-facing progress messages.
    pub on_progress: Option<ProgressFn>,
}

impl Clone for ToolContext {
    /*
    In Rust, there is no automatic copying of complex structs — when you assign or pass a struct, ownership moves, meaning the original is gone.
    For ToolContext, we want to be able to clone it (e.g., if multiple tool calls share the same context), so we implement the Clone trait manually.
    When multiple tools run in parallel, each tool must own its own ToolContext instance (its own cancel token, its own on_progress callback) —
    you can't move one context into two threads simultaneously . clone() is what makes that fan-out safe.

    Clone is a trait (like From<Message>) that allows for explicit duplication of values.
    By implementing Clone for ToolContext, we can create independent copies of the context for each tool execution,
    ensuring thread safety and proper ownership semantics in concurrent scenarios.
    A Trait in Rust gets implemented by the "for" preposition — impl TraitName for Type { ... }
    — this is how you say "this type implements this trait, and here are the method definitions that fulfill the trait's contract".

    An example of traits and its usage in Rust:

    // Define the trait (the ABC skeleton)
    trait Summarizable {
        fn summary(&self) -> String;                  // must implement
        fn label(&self) -> String {                   // optional default
            String::from("item")
        }
    }

    // Implement it for a struct
    struct AgentEvent { text: String }

    impl Summarizable for AgentEvent {
        fn summary(&self) -> String {
            format!("Event: {}", self.text)           // must provide this
        }
        // label() is inherited from default
    }

    */
    fn clone(&self) -> Self {
        Self {
            tool_call_id: self.tool_call_id.clone(),
            tool_name: self.tool_name.clone(),
            cancel: self.cancel.clone(),
            on_update: self.on_update.clone(),
            on_progress: self.on_progress.clone(),
        }
    }
}

impl std::fmt::Debug for ToolContext {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        /*
        <'_> — Lifetime Elision Syntax: In Rust, when you see a lifetime annotation like <'_>,
        it means "I want the compiler to infer the appropriate lifetime for this reference."
        "how long a borrow is valid"
         In the context of the Debug implementation for ToolContext, the on_update and on_progress fields are Arc-wrapped function pointers (callbacks).
         These callbacks may capture references to data with specific lifetimes, but since we're only printing a placeholder ("<callback>") instead of the actual function,
         we don't need to worry about their lifetimes here. The <'_> allows us to implement Debug without having to specify or manage those lifetimes explicitly.

        &self.on_update.as_ref().map(|_| "<callback>")
        This line is a clever way to indicate in the debug output that there is a callback present without trying to print the actual function pointer
        (which isn't useful and can be complex).
        on_update is Option<Arc<dyn Fn(...)>> — an optional function pointer wrapped in an Arc (shared pointer) . The logic here is:

            .as_ref() — peek at the Option without consuming it

            .map(|_| "<callback>") — if it exists, replace it with the string "<callback>" for display purposes; if None, stays None

            The |_| is a closure that ignores its argument (the actual Arc) and just returns the label "<callback>" to indicate that a callback is present.

        Why? Because you can't Debug-print a function/closure — so this substitutes a human-readable placeholder.
        "<callback>" is just a string literal they chose; it has no special Rust meaning.
        */
        f.debug_struct("ToolContext")
            .field("tool_call_id", &self.tool_call_id)
            .field("tool_name", &self.tool_name)
            .field("cancel", &self.cancel)
            .field("on_update", &self.on_update.as_ref().map(|_| "<callback>"))
            .field(
                "on_progress",
                &self.on_progress.as_ref().map(|_| "<callback>"),
            )
            .finish()
    }
}

/// A tool the agent can call. Implement this trait for your tools.
/*
JUST A NOTE ON ASYNC TRAITS:
Rust traits natively can't have async fn methods (pre-2024 stable),
so this macro rewrites your async fn execute(...) into a fn execute(...) -> Pin<Box<dyn Future>> under the hood.
*/
#[async_trait::async_trait]
pub trait AgentTool: Send + Sync {
    /// Unique tool name (used in LLM tool_use)
    fn name(&self) -> &str;
    /// Human-readable label for UI
    fn label(&self) -> &str;
    /// Description for the LLM
    fn description(&self) -> &str;
    /// JSON Schema for parameters
    fn parameters_schema(&self) -> serde_json::Value;
    /// Execute the tool.
    ///
    /// The `ctx` parameter provides per-invocation context:
    /// - `ctx.tool_call_id` / `ctx.tool_name` — for correlation and logging
    /// - `ctx.cancel` — cancellation token; check `is_cancelled()` in long-running tools
    /// - `ctx.on_update` — optional callback for streaming partial `ToolResult`s (UI/logging only)
    /// - `ctx.on_progress` — optional callback for user-facing progress text (`ProgressMessage`)
    /*
    DESIGN: Why `params` AND `ctx` are separate parameters — input vs environment
      `params`  = LLM INPUT    — the JSON arguments the LLM chose to pass this invocation;
                                 varies per call (e.g. {"cmd": "ls -la"} one call, {"cmd": "pwd"} next)
      `ctx`     = SYSTEM ENV   — plumbing injected by the agent loop; same shape for every tool:
                                 cancel token, on_update callback, on_progress callback, call identifiers
    The separation keeps tools clean: a tool's execute() only needs to know about its own args
    (params), while the system concerns (how to cancel, how to stream updates) are injected via ctx.
    Python analogy: params ~ **kwargs from the caller; ctx ~ a request context object from the framework.
    */
    async fn execute(
        &self,
        params: serde_json::Value, // LLM INPUT — JSON args chosen by the LLM; validated inside execute()
        ctx: ToolContext, // SYSTEM ENV — cancel token + streaming callbacks from the agent loop
    ) -> Result<ToolResult, ToolError>;
}

// ---------------------------------------------------------------------------
// Agent events (for streaming UI updates)
// ---------------------------------------------------------------------------

/// How an `agent_loop_continue` call relates to the session's prior loops.
///
/// Set on [`AgentContext::continuation_kind`] before calling `agent_loop_continue`,
/// and surfaced in [`AgentEvent::AgentStart`] so that observability consumers
/// (logs, UIs, analysis tools) can understand the session execution tree without
/// inspecting message content.
///
/// The runtime does **not** enforce context constraints — e.g. it does not verify
/// that a `Rerun` uses an identical context to the original loop. That is the caller's
/// responsibility. The distinction is purely semantic / for traceability.
#[derive(Debug, Clone, PartialEq)]
pub enum ContinuationKind {
    /// Unspecified continuation — preserves the original `agent_loop_continue` semantics.
    /// Use when the Rerun/Branch distinction is not relevant to the caller.
    Default,
    /// Retry of the same scenario from an equivalent context state.
    ///
    /// The `tag` is an RFC 3339 UTC timestamp auto-generated at call time.
    /// Use for error recovery, rate-limit retries, or explicit re-runs.
    Rerun { tag: String },
    /// Exploration of a different execution path from a specific branching point.
    ///
    /// The `tag` is an RFC 3339 UTC timestamp auto-generated at call time.
    /// Caller should modify `context.messages` to set up the alternative path
    /// before calling `agent_loop_continue`. The first turn emits
    /// [`TurnTrigger::Branch`] instead of `FollowUp`.
    Branch { tag: String },
}

/// Identifies what caused a new turn to begin.
#[derive(Debug, Clone)]
pub enum TurnTrigger {
    /// First turn triggered by a user message (`agent_loop`).
    User,
    /// This agent was invoked as a sub-agent by a parent agent.
    SubAgent,
    /// Continuation turn: tool round-trip, steering message, or `Default` / `Rerun` continuation.
    FollowUp,
    /// First turn of a `Branch` continuation (`agent_loop_continue` with `ContinuationKind::Branch`).
    /// Subsequent turns within the same branched loop use `FollowUp`.
    Branch,
}

#[derive(Debug, Clone)]
pub enum AgentEvent {
    /*********************** NOTEs ON AGENT EVENTS *************************
    AgentEvent is the runtime's event vocabulary — it captures all the significant happenings
    in the agent loop that the UI or other consumers might want to react to.
    This includes LLM-related events (message start/update/end, tool execution start/update/end)
    as well as more general events (agent start/end, turn start/end, input rejected).
    The key design principle is that AgentEvent should be comprehensive enough
    to capture all relevant state changes and milestones in the agent's operation,
    without being too tightly coupled to the specifics of any one LLM provider.

    ********************* SOME IMPROVEMENTS TO CONSIDER FOR AGENT EVENTS *************************
    1. More granular turn events: e.g., separate events for "LLM call start", "LLM call end",
    "tool calls start", "tool call end" within a turn, to give the UI more hooks for showing loading
    states, progress bars, etc.

    2. Error events: a dedicated AgentEvent variant for errors that occur during the agent loop
    (e.g., LLM call failures, tool execution errors) to allow the UI to react specifically
    to errors (e.g., show error messages, retry buttons).

    3. Input events: events for when user input is received, validated, rejected, etc.,
    to give the UI more hooks for showing input-related feedback.

    */
    /// Fires once when agent_loop() is entered — before any LLM call.
    /// UI use: show "thinking..." spinner, clear previous output, record start time.
    AgentStart {
        /// Stable identifier for this agent instance. Caller-supplied or auto-generated UUID v4.
        agent_id: String,
        /// Identifier for the current session. Groups related loops under one logical umbrella.
        /// Persists across multiple `agent_loop()` / `agent_loop_continue()` calls.
        session_id: String,
        /// Unique identifier for this specific loop call within the session.
        /// Format: `"{session_id}.{config_id}.{N}"` — encodes which config produced this loop.
        /// Auto-derived from provider + model + thinking_level when not explicitly set.
        loop_id: String,
        /// The `loop_id` of the loop this continues from. `None` for origin calls
        /// (`agent_loop()` with no prior session). Set for all `agent_loop_continue()` calls.
        parent_loop_id: Option<String>,
        /// How this continuation relates to prior loops. `None` for origin calls.
        /// `Some(Default|Rerun|Branch)` for `agent_loop_continue()` calls.
        continuation_kind: Option<ContinuationKind>,
        /// Wall-clock time when the agent loop was entered.
        timestamp: chrono::DateTime<chrono::Utc>,
        /// Extensible bag for caller-supplied context (e.g., user info, request tags, trace IDs).
        /// Passed through as-is — the agent loop does not read or modify this field.
        metadata: Option<serde_json::Value>,
    },

    /// Fires once when agent_loop() exits — after all turns and follow-ups complete.
    /// UI use: hide spinner, render final output, log token cost from the last assistant message.
    AgentEnd {
        /// All new messages added during this run (not the full history).
        /// Empty when `rejection` is `Some` — input was blocked before the LLM was called.
        messages: Vec<AgentMessage>,
        /// Total token usage accumulated across all turns in this run.
        /// All fields are 0 when `rejection` is `Some` (no LLM calls were made).
        usage: Usage,
        /// Wall-clock time when the agent loop exited.
        timestamp: chrono::DateTime<chrono::Utc>,
        /// `Some(reason)` when an InputFilter rejected the input before any LLM call.
        /// `None` on normal exit. When `Some`, `messages` will be empty.
        rejection: Option<String>,
    },

    /// Fires at the start of each LLM turn (one LLM call = one turn).
    /// A single agent run may have many turns: initial response + one per tool-call round-trip.
    /// UI use: show "waiting for LLM..." indicator between tool results and the next response.
    TurnStart {
        /// Zero-based index of this turn within the current agent run (0 = first turn after AgentStart).
        turn_index: u32,
        /// Wall-clock time when this turn began.
        timestamp: chrono::DateTime<chrono::Utc>,
        /// What caused this turn to begin. Distinguishes user-initiated turns from
        /// system continuations (tool round-trips, follow-ups, sub-agent invocations).
        triggered_by: TurnTrigger,
    },

    /// Fires at the end of each LLM turn, carrying the assistant message and all tool results.
    /// UI use: close the turn's loading indicator; `tool_results` can be shown as a collapsible block.
    TurnEnd {
        /// The assistant message produced this turn (may include text, thinking, and tool calls).
        message: AgentMessage,
        /// Token usage for this turn — direct access without destructuring `message`.
        /// Useful for per-turn cost tracking and rate-limit management.
        usage: Usage,
        /// Wall-clock time when this turn completed (after all tool calls finished executing).
        timestamp: chrono::DateTime<chrono::Utc>,
        /// Executed tool results from this turn. Empty when no tool calls were made (`StopReason::Stop`).
        /// These are the results fed back to the LLM — distinct from `message.content` which holds
        /// the LLM's tool call *requests*.
        tool_results: Vec<Message>,
    },

    /// Fires when a new message object is first created (before streaming content).
    /// For LLM assistant messages: fires when the SSE stream opens (StreamEvent::Start).
    /// For user/tool messages:      fires immediately (they're complete on creation).
    /// UI use: create a placeholder message bubble in the chat UI.
    MessageStart { message: AgentMessage },

    /// Fires for each streaming token/chunk as the LLM generates content.
    /// `delta` carries the incremental update — text token, thinking chunk, or tool-call JSON piece.
    /// `message` is the current accumulated state (useful if you join late and missed earlier deltas).
    /// UI use: append delta to the message bubble — this is what makes "typing" animations work.
    MessageUpdate {
        message: AgentMessage,
        delta: StreamDelta,
    },

    /// Fires when a message is fully complete (all tokens received).
    /// `message` is the final, complete message — safe to persist or hand off.
    /// UI use: finalize the message bubble, enable copy/share actions.
    MessageEnd { message: AgentMessage },

    /// Fires when a tool call begins execution (before execute() is called).
    /// `args` is the raw JSON the LLM sent — useful for showing "what the agent is doing".
    /// UI use: show "[tool_name] running with args: ..." status line.
    ToolExecutionStart {
        tool_call_id: String,
        tool_name: String,
        args: serde_json::Value,
    },

    /// Fires when a tool streams a partial result mid-execution (via ctx.on_update).
    /// Not all tools emit these — only long-running tools that support streaming output.
    /// UI use: update a live output preview (e.g., bash command output as it streams in).
    ToolExecutionUpdate {
        tool_call_id: String,
        tool_name: String,
        partial_result: ToolResult,
    },

    /// Fires when a tool finishes execution (success or error).
    /// `is_error: true` means the tool failed but the LLM will see the error and can retry/recover.
    /// `result.content` is what gets appended as Message::ToolResult into the conversation.
    /// UI use: mark the tool status as done/failed; show final output in the tool block.
    ToolExecutionEnd {
        tool_call_id: String,
        tool_name: String,
        result: ToolResult,
        is_error: bool,
        /// Set to the child agent's `loop_id` when this tool spawned a sub-agent loop.
        /// `None` for all regular (non-sub-agent) tools.
        /// Enables parent→child traceability in the event stream without parsing tool result text.
        child_loop_id: Option<String>,
    },

    /// Fires when a tool emits a user-facing status string (via ctx.on_progress).
    /// Unlike ToolExecutionUpdate (structured partial results), this is plain text for display.
    /// Example: a bash tool might emit "Installing dependencies..." before the final output.
    /// UI use: show as a transient status line / toast notification under the tool block.
    ProgressMessage {
        tool_call_id: String,
        tool_name: String,
        text: String,
    },

    /// Fires when an InputFilter rejects the user's message before the LLM is called.
    /// `reason` is the human-readable explanation from the filter (e.g., "PII detected").
    /// The agent loop returns immediately after emitting this — no LLM call is made.
    /// UI use: show an error banner; do NOT bubble this up as a normal message.
    InputRejected { reason: String },
}

/*
StreamDelta — incremental token-level updates from the LLM stream.

Why is this a separate enum from AgentEvent?
Because streaming is a different concern from messaging. A MessageUpdate carries:
  1. the partial message accumulator (so late subscribers can catch up), AND
  2. just the new delta (so efficient UIs only re-render the new bit)

Having a dedicated StreamDelta enum lets you switch in the UI:
  match delta {
      StreamDelta::Text { delta }        => append_text(delta),
      StreamDelta::Thinking { delta }    => append_thinking(delta),
      StreamDelta::ToolCallDelta { delta } => accumulate_tool_json(delta),
  }

StreamDelta::ToolCallDelta carries raw JSON fragments as the LLM streams tool
argument JSON (e.g., `{"path": "src/ma` ... `in.rs"}`). The receiver must
accumulate and parse these into a complete JSON value only after MessageEnd.
*/
#[derive(Debug, Clone)]
pub enum StreamDelta {
    /// A text token fragment from the LLM's response.
    Text { delta: String },
    /// A thinking/reasoning chunk (extended thinking mode only).
    Thinking { delta: String },
    /// A fragment of the JSON arguments for a tool call (accumulate until MessageEnd).
    ToolCallDelta { delta: String },
}

// ---------------------------------------------------------------------------
// Agent context (passed to the loop)
// ---------------------------------------------------------------------------

#[derive(Default)]
pub struct AgentContext {
    /*
    AgentContext vs Agent Session
    AgentContext is a snapshot — the minimal state needed to execute one agent loop call:
    system prompt + message history + available tools . It's stateless and passed around
    functionally.

    An Agent Session (your extension target) would be the lifecycle wrapper —
    tracking session ID, branch tree, timestamps, and multiple AgentContext snapshots over time.
    Think of it as: AgentContext is a single frame, a Session is the whole film reel.
    */
    pub system_prompt: String, // PROMPT — injected at the top of every LLM call (role="system")
    pub messages: Vec<AgentMessage>, // HISTORY — full conversation; grows each turn; includes Extension messages

    // dyn: "I don't know the concrete type at compile time, but it implements the AgentTool trait"
    // Box: "I want to store this on the heap because it might be a large or complex type,
    // and I want to use dynamic dispatch to call its methods". In plain terms, Box is a heap-allocated pointer wrapper
    // — because Rust needs to know the size of everything at compile time, and different tool structs have different sizes,
    // so you box them to a fixed-size pointer.
    pub tools: Vec<Box<dyn AgentTool>>, // REGISTRY — available tool implementations; converted to ToolDefinition for LLM

    // ── Identity ─────────────────────────────────────────────────────────────
    // Set by callers (e.g. Agent wrapper) before each loop call.
    // agent_loop() auto-generates UUIDs if None and writes them back to context.
    // agent_loop_continue() asserts both are Some — continuations require stable identity.
    /// Stable identifier for the agent instance. Auto-generated UUID v4 if None on first call;
    /// written back to context so continuations inherit it.
    pub agent_id: Option<String>,

    /// Groups related loop calls under one logical session (evaluational parallelism, reruns,
    /// branches). Auto-generated UUID v4 if None on first call; written back to context.
    /// Required (Some) for all `agent_loop_continue()` calls.
    pub session_id: Option<String>,

    /// Unique identifier for this specific loop call: `"{session_id}.{config_id}.{N}"`.
    /// Set by Agent wrapper via `next_loop_id()`; direct callers may supply their own.
    /// Falls back to a UUID at loop entry if still None.
    pub loop_id: Option<String>,

    /// The `loop_id` of the loop this was continued from. None for origin calls.
    /// Set by Agent wrapper for `agent_loop_continue()` calls to enable ancestry tracking.
    pub parent_loop_id: Option<String>,

    /// How this loop relates to prior loops. None for origin calls.
    /// Some(Default|Rerun|Branch) for agent_loop_continue() calls.
    pub continuation_kind: Option<ContinuationKind>,
}

// ---------------------------------------------------------------------------
// Input filtering
// ---------------------------------------------------------------------------

/// Result of applying an input filter to a user message.
#[derive(Debug, Clone)]
pub enum FilterResult {
    /// Message passes unchanged.
    Pass,
    /// Message passes, but append a warning to context for the LLM to see.
    Warn(String),
    /// Message is rejected. Agent loop returns immediately.
    Reject(String),
}

/// Synchronous filter applied to user input before the LLM call.
///
/// Implement this for injection detection, content moderation, PII redaction, etc.
/// Filters run in the hot path and must be fast — use `before_turn` callbacks
/// for async moderation (external API calls).
/*
RUST QUIRK: Trait as interface (no `async` here — intentional)

InputFilter is deliberately *synchronous*. Why? Filters run in the hot path
before every LLM call. Async would require `.await`, which adds complexity
and forces callers into async context. For CPU-bound work (regex, keyword scan)
synchronous is faster.

For async filtering (external API call to a moderation service), use the
`before_turn` callback hook instead — it's async and can return false to abort.

The `Send + Sync` supertrait bounds mean:
  Send  → the filter can be moved to another thread
  Sync  → the filter can be shared by reference across threads

These are required because filters are stored in `Vec<Arc<dyn InputFilter>>`
inside AgentLoopConfig. The agent loop may run on any tokio thread, so the
filters must be thread-safe.

Python analogy: an abstract base class with one required method:
  class InputFilter(ABC):
      @abstractmethod
      def filter(self, text: str) -> FilterResult: ...
*/
pub trait InputFilter: Send + Sync {
    fn filter(&self, text: &str) -> FilterResult;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/*
now_ms() — current time as Unix milliseconds (ms since Jan 1, 1970 UTC).

RUST QUIRK: Rust's time API is intentionally explicit about fallibility.
`duration_since(UNIX_EPOCH)` returns a Result<Duration, SystemTimeError>
because in theory the system clock could be set before the epoch (negative).
`.unwrap_or_default()` handles this gracefully: if it fails, use Duration::ZERO
(timestamp = 0) rather than panicking. Panicking in a timestamp helper would
be a terrible user experience.

Chain breakdown:
  SystemTime::now()              → current system time (platform-specific)
  .duration_since(UNIX_EPOCH)   → Result<Duration, SystemTimeError>
  .unwrap_or_default()           → Duration (0 on error)
  .as_millis()                   → u128 (milliseconds as 128-bit integer)
  as u64                         → truncate to 64-bit (safe until year 584,542,046)

Python analogy:
  import time
  now_ms = int(time.time() * 1000)
*/
pub fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis() as u64
}
